package com.tianya.dao3;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import com.tianya.entity.TElement;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface TElementMapper extends BaseMapper<TElement> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_element
     *
     * @mbg.generated
     */
    TElement selectByPrimaryKey(Long fElementId);

    int insertSelective(TElement element);

    TElement selectByPrimaryKeyLock(Long fElementId);

    @Update({"UPDATE t_element SET f_element_status=#{status} WHERE f_element_id >= #{elementId}"})
    int update(long elementId, byte status);

    @Select({"select count(*) from t_element where f_element_status=#{status}"})
    Long select(byte status);

    @Update({"UPDATE t_element SET f_element_status=#{status} WHERE f_element_id=#{elementId} AND f_element_status=1"})
    int updateHappy(long elementId, byte status);
}