package com.tianya.entity;

import com.baomidou.mybatisplus.annotation.TableId;

import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_element
 */
public class TElement implements Serializable  {
    /**
     * Database Column Remarks:
     *   要素自增主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_element.F_element_id
     *
     * @mbg.generated
     */
    @TableId
    private Long fElementId;

    /**
     * Database Column Remarks:
     *   要素名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_element.F_element_name
     *
     * @mbg.generated
     */
    private String fElementName;

    /**
     * Database Column Remarks:
     *   功能状态 1.enabled 2.disabled
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_element.F_element_status
     *
     * @mbg.generated
     */
    private Byte fElementStatus;

    /**
     * Database Column Remarks:
     *   记录创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_element.F_create_time
     *
     * @mbg.generated
     */
    private Date fCreateTime;

    /**
     * Database Column Remarks:
     *   最后修改时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_element.F_modify_time
     *
     * @mbg.generated
     */
    private Date fModifyTime;

    /**
     * Database Column Remarks:
     *   扩展字段
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_element.F_extension
     *
     * @mbg.generated
     */
    private String fExtension;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_element.F_element_id
     *
     * @return the value of t_element.F_element_id
     *
     * @mbg.generated
     */
    public Long getfElementId() {
        return fElementId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_element.F_element_id
     *
     * @param fElementId the value for t_element.F_element_id
     *
     * @mbg.generated
     */
    public void setfElementId(Long fElementId) {
        this.fElementId = fElementId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_element.F_element_name
     *
     * @return the value of t_element.F_element_name
     *
     * @mbg.generated
     */
    public String getfElementName() {
        return fElementName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_element.F_element_name
     *
     * @param fElementName the value for t_element.F_element_name
     *
     * @mbg.generated
     */
    public void setfElementName(String fElementName) {
        this.fElementName = fElementName == null ? null : fElementName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_element.F_element_status
     *
     * @return the value of t_element.F_element_status
     *
     * @mbg.generated
     */
    public Byte getfElementStatus() {
        return fElementStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_element.F_element_status
     *
     * @param fElementStatus the value for t_element.F_element_status
     *
     * @mbg.generated
     */
    public void setfElementStatus(Byte fElementStatus) {
        this.fElementStatus = fElementStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_element.F_create_time
     *
     * @return the value of t_element.F_create_time
     *
     * @mbg.generated
     */
    public Date getfCreateTime() {
        return fCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_element.F_create_time
     *
     * @param fCreateTime the value for t_element.F_create_time
     *
     * @mbg.generated
     */
    public void setfCreateTime(Date fCreateTime) {
        this.fCreateTime = fCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_element.F_modify_time
     *
     * @return the value of t_element.F_modify_time
     *
     * @mbg.generated
     */
    public Date getfModifyTime() {
        return fModifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_element.F_modify_time
     *
     * @param fModifyTime the value for t_element.F_modify_time
     *
     * @mbg.generated
     */
    public void setfModifyTime(Date fModifyTime) {
        this.fModifyTime = fModifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_element.F_extension
     *
     * @return the value of t_element.F_extension
     *
     * @mbg.generated
     */
    public String getfExtension() {
        return fExtension;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_element.F_extension
     *
     * @param fExtension the value for t_element.F_extension
     *
     * @mbg.generated
     */
    public void setfExtension(String fExtension) {
        this.fExtension = fExtension == null ? null : fExtension.trim();
    }
}